version: "3.4"

services:
  crawler:
    build:
      context: .
    tty: true
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: links_crawler.settings
      IPYTHONDIR: /opt/.ipython
      REDIS_URL: redis://crawler_cache:6379/
    links:
      - crawler_cache
      - celery_worker
    ports:
      -  "${APP_PORT:-8000}:8000"
    depends_on:
      - crawler_cache
      - celery_worker
    volumes:
      - .:/opt:cached
      - .bash_history:/root/.bash_history:cached

  crawler_cache:
    image: redis:6.2.4-alpine

  celery_worker:
    build:
      context: .
    command: ['celery', '-A', 'links_crawler.celery', 'worker', '-l', 'info']
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: links_crawler.settings
      REDIS_URL: redis://crawler_cache:6379/
    volumes:
      - .:/opt:cached
      - .bash_history:/root/.bash_history:cached


