version: "3.4"

services:
  crawler:
    build:
      context: .
    tty: true
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: links_crawler.settings
      REDIS_URL: redis://social_cache:6379/
    links:
      - crawler_cache
    ports:
      -  "${APP_PORT:-8000}:8000"  # runserver
    depends_on:
      - crawler_cache
    volumes:
      - .:/opt:cached
      - .bash_history:/root/.bash_history:cached

  crawler_cache:
    image: redis:6.2.4-alpine
